apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.fullName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.selectorLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullName}}
    spec:
      containers:
        - name: {{ .Values.container.name}}
          image: {{ .Values.container.image}}
          imagePullPolicy: {{ .Values.container.pullPolicy}}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: api
              protocol: TCP
          env:
            - name: api.Port
              value: "{{ .Values.service.port }}"
            - name: postgres.Host
              value: "solenopsys-ds-postgres.default.svc.cluster.local"
            - name: postgres.Port
              value: "5432"
            - name: postgres.Password
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pg-password
                  optional: false
            - name: postgres.User
              value: postgres